CREATE VIEW
  `gcp-de-dev-bi.cur_dtm.v_dim_product_bu_listing` AS
SELECT
  sid_sales_org sid_bu,
  sid_sales_org,
  sid_product,
  sid_product_distribution_chnl sid_distribution_chnl,
  product id_product,
  product_sales_org id_sales_org,
  product_distribution_chnl id_distribution_chnl,
  minimum_order_quantity,
  supplying_plant,
  price_specification_product_group,
  account_detn_product_group,
  delivery_note_proc_min_deliv_qty,
  item_category_group,
  delivery_quantity_unit,
  delivery_quantity,
  product_sales_status,
  product_sales_status_validity_date,
  sales_measure_unit,
  is_marked_for_deletion,
  product_hierarchy,
  first_sales_spec_product_group,
  second_sales_spec_product_group,
  third_sales_spec_product_group,
  fourth_sales_spec_product_group,
  fifth_sales_spec_product_group,
  minimum_make_to_order_qty,
  logistics_statistics_group,
  volume_rebate_group,
  product_commission_group,
  is_cash_discount_deductible,
  pricing_reference_product,
  assortment_grade,
  store_listing_procedure,
  distr_cntr_listing_procedure,
  store_listing_start_date,
  store_listing_end_date,
  distr_cntr_listingstartdate distr_cntr_listing_start_date,
  distrcntrlistingenddate distr_cntr_listing_en_ddate,
  storesalestartdate store_sale_start_date,
  storesaleenddate store_sale_en_ddate,
  distrcntrsalestartdate distr_cntr_sale_start_date,
  roundingprofile rounding_profile,
  productunitgroup product_unit_group,
  maxdeliveryqtystoreorder max_delivery_qty_store_order,
  pricefixingcategory price_fixing_category,
  variable_sales_unit_is_not_allowed,
  competition_pressure_category,
  product_has_attribute_id01,
  product_has_attribute_id02,
  product_has_attribute_id03,
  product_has_attribute_id04,
  product_has_attribute_id05,
  product_has_attribute_id06,
  product_has_attribute_id07,
  product_has_attribute_id08,
  product_has_attribute_id09,
  product_has_attribute_id10,
  is_active_entity,
  prodext_assortment_priority,
  prod_is_entlmnt_rlvt,
  base_unit,
  subscrpn_contr_dflt_duration,
  subscrpn_contr_altv_duration1,
  subscrpn_contr_altv_duration2,
  subscrpn_contr_duration_unit,
  subscrpn_contr_dflt_extn_durn,
  subscrpn_contr_altv_extn_durn1,
  subscrpn_contr_altv_extn_durn2,
  subscrpn_contr_extn_durn_unit,
  operation,
  curr_flag,
  `source`,
  load_date
FROM
  `gcp-de-dev-bi.cur_dwh.dim_product_bu_listing`;