CREATE TABLE
  `gcp-de-dev-bi.cur_dwh.dim_product_logistic_md` ( sid_product STRING NOT NULL,
    unit_of_issue STRING,
    GTIN_UPC INT64,
    packaging_desc_en STRING,
    packaging_desc_fr STRING,
    packaging_weight_metric FLOAT64,
    packaging_weight_UOM_metric STRING,
    packaging_weight_imperial FLOAT64,
    packaging_weight_UOM_imperial STRING,
    packaging_height_metric FLOAT64,
    packaging_height_imperial FLOAT64,
    packaging_width_metric FLOAT64,
    packaging_width_imperial FLOAT64,
    packaging_depth_metric FLOAT64,
    packaging_depth_imperial FLOAT64,
    packaging_volume_cube_metric FLOAT64,
    packaging_volume_cube_imperial FLOAT64,
    packaging_dimension_UOM_metric STRING,
    packaging_dimension_UOM_imperial STRING,
    item_class STRING,
    dangerous_goods STRING,
    harmonization_code STRING,
    base_qty INT64,
    GTIN_UPC_type STRING,
    country_of_origin STRING,
    whmis STRING,
    stackable STRING,
    max_stack STRING,
    rotation_factor STRING,
    report_run_date TIMESTAMP,
    extract_full_delta STRING,
    SOURCE STRING NOT NULL,
    load_date TIMESTAMP NOT NULL );